### ISSUE TITLE
content image

### ISSUE THREAD

**Issue by geyanqi** [FreeStyleFreeLunch/FreeStyle#2] opened 2024-02-21 08:13 UTC
The content images appear to be generated directly from SDXL. Can you provide some transfer results on real images with irregularities? For example, there are no restrictions on resolution or image quality. 

and the second row of eq4 is hard to understand. how do input an image without a text prompt into diffusion models?

In addition, the code has so many bugs that need to be fixed.

**Comment by geyanqi** [comment] 2024-02-21 09:58
and the second row of eq4 is hard to understand. How to input an image without a text prompt into a diffusion model?

**Comment by geyanqi** [comment] 2024-02-21 14:45
Thank you for your reply. 

But the purpose of transferring the style of generated images is unclear. More commonly used real images may need to be checked, such as those in imagenet-R dataset. 

In addition, can you explain the second row of eq4 further?

**Comment by FreeStyleFreeLunch** [comment] 2024-02-22 01:04
We adopted a similar evaluation method as referenced in other papers. Eq4 represents the process of downsampling the content images without adding noise.

**Comment by FreeStyleFreeLunch** [comment] 2024-02-22 01:04
I believe I have fixed the bug in the code and I am going to close this issue.

**Comment by geyanqi** [comment] 2024-02-22 07:00
The bug still exists and I get the following return,
```
Traceback (most recent call last):
  File "stable_diffusion_xl_test.py", line 434, in <module>
    test(args)
  File "stable_diffusion_xl_test.py", line 312, in test
    outputs = pipeline(
  File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data0/geyanqi/stylefree/diffusers_test/pipeline_stable_diffusion_xl.py", line 818, in __call__
    ) = self.encode_prompt(
  File "/data0/geyanqi/stylefree/diffusers_test/pipeline_stable_diffusion_xl.py", line 348, in encode_prompt
    prompt_embeds = text_encoder(
  File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 798, in forward
    return self.text_model(
  File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 703, in forward
    encoder_outputs = self.encoder(
  File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 630, in forward
    layer_outputs = encoder_layer(
  File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 371, in forward
    hidden_states = self.layer_norm1(hidden_states)
  File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/nn/modules/normalization.py", line 201, in forward
    return F.layer_norm(
  File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/nn/functional.py", line 2546, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'
```

**Comment by geyanqi** [comment] 2024-02-22 07:06
> The bug still exists and I get the following return,
> 
> ```
> Traceback (most recent call last):
>   File "stable_diffusion_xl_test.py", line 434, in <module>
>     test(args)
>   File "stable_diffusion_xl_test.py", line 312, in test
>     outputs = pipeline(
>   File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
>     return func(*args, **kwargs)
>   File "/data0/geyanqi/stylefree/diffusers_test/pipeline_stable_diffusion_xl.py", line 818, in __call__
>     ) = self.encode_prompt(
>   File "/data0/geyanqi/stylefree/diffusers_test/pipeline_stable_diffusion_xl.py", line 348, in encode_prompt
>     prompt_embeds = text_encoder(
>   File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 798, in forward
>     return self.text_model(
>   File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 703, in forward
>     encoder_outputs = self.encoder(
>   File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 630, in forward
>     layer_outputs = encoder_layer(
>   File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 371, in forward
>     hidden_states = self.layer_norm1(hidden_states)
>   File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
>     return self._call_impl(*args, **kwargs)
>   File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
>     return forward_call(*args, **kwargs)
>   File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/nn/modules/normalization.py", line 201, in forward
>     return F.layer_norm(
>   File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/nn/functional.py", line 2546, in layer_norm
>     return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
> RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'
> ```

This problem seems to be related to my gpu-driver. But can you provide a gpu driver-friendly installation method?

**Comment by geyanqi** [comment] 2024-02-22 07:11
> We adopted a similar evaluation method as referenced in other papers. Eq4 represents the process of downsampling the content images without adding noise.

So, how to input the content image embedding into unet-encoder? The original Unet-encoder needs text embedding and latent embedding to work together for cross-attention.

**Comment by ucasligang** [comment] 2024-02-22 08:48
> > The bug still exists and I get the following return,
> > ```
> > Traceback (most recent call last):
> >   File "stable_diffusion_xl_test.py", line 434, in <module>
> >     test(args)
> >   File "stable_diffusion_xl_test.py", line 312, in test
> >     outputs = pipeline(
> >   File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
> >     return func(*args, **kwargs)
> >   File "/data0/geyanqi/stylefree/diffusers_test/pipeline_stable_diffusion_xl.py", line 818, in __call__
> >     ) = self.encode_prompt(
> >   File "/data0/geyanqi/stylefree/diffusers_test/pipeline_stable_diffusion_xl.py", line 348, in encode_prompt
> >     prompt_embeds = text_encoder(
> >   File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
> >     return self._call_impl(*args, **kwargs)
> >   File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
> >     return forward_call(*args, **kwargs)
> >   File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 798, in forward
> >     return self.text_model(
> >   File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
> >     return self._call_impl(*args, **kwargs)
> >   File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
> >     return forward_call(*args, **kwargs)
> >   File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 703, in forward
> >     encoder_outputs = self.encoder(
> >   File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
> >     return self._call_impl(*args, **kwargs)
> >   File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
> >     return forward_call(*args, **kwargs)
> >   File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 630, in forward
> >     layer_outputs = encoder_layer(
> >   File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
> >     return self._call_impl(*args, **kwargs)
> >   File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
> >     return forward_call(*args, **kwargs)
> >   File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 371, in forward
> >     hidden_states = self.layer_norm1(hidden_states)
> >   File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
> >     return self._call_impl(*args, **kwargs)
> >   File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
> >     return forward_call(*args, **kwargs)
> >   File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/nn/modules/normalization.py", line 201, in forward
> >     return F.layer_norm(
> >   File "/data0/geyanqi/miniconda3/envs/stylefree/lib/python3.8/site-packages/torch/nn/functional.py", line 2546, in layer_norm
> >     return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
> > RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'
> > ```
> 
> This problem seems to be related to my gpu-driver. But can you provide a gpu driver-friendly installation method?

Thank you very much for your interest in our work. This problem may be caused by your GPU driver being too old, it is recommended to upgrade the GUP driver from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. We conducted tests on two different servers. The GPU driver version 535.154.05-0ubuntu0.20.04.1 operates normally, while version 515.105.01-0ubuntu1 encounters the same error, the GPU we use is V100. Therefore, it is strongly recommended to upgrade the corresponding GPU drivers based on your GPU type.

**Comment by ucasligang** [comment] 2024-02-22 08:54
> > We adopted a similar evaluation method as referenced in other papers. Eq4 represents the process of downsampling the content images without adding noise.
> 
> So, how to input the content image embedding into unet-encoder? The original Unet-encoder needs text embedding and latent embedding to work together for cross-attention.
![image](https://github.com/FreeStyleFreeLunch/FreeStyle/assets/46208141/391fb683-77ef-4594-9106-ade3165390fb)

As shown in Figure 2 of the paper, our FreeStyle consists of two visual encoder branches, where the lower branch takes the clean content image as input.

**Comment by geyanqi** [comment] 2024-02-23 07:16
However the lower branch in the code also enters text embedding.

https://github.com/FreeStyleFreeLunch/FreeStyle/blob/main/diffusers_test/pipeline_stable_diffusion_xl.py#L1007,
https://github.com/FreeStyleFreeLunch/FreeStyle/blob/main/diffusers_test/pipeline_stable_diffusion_xl.py#L1018

**Comment by geyanqi** [comment] 2024-02-23 07:29
Furthermore, I think you can mark out the key parts of the code in the README file to help others quickly understand your work. If I understand correctly, this part should be in:

upper branch:
1. https://github.com/FreeStyleFreeLunch/FreeStyle/blob/main/diffusers_test/pipeline_stable_diffusion_xl.py#L1007
skip_stack == None 
2. https://github.com/FreeStyleFreeLunch/FreeStyle/blob/main/diffusers/src/diffusers/models/unet_2d_condition.py#L976
return the unet encoder features to skip_stack, 

lower branch:
3.  https://github.com/FreeStyleFreeLunch/FreeStyle/blob/main/diffusers_test/pipeline_stable_diffusion_xl.py#L1018
use step2's skip_stach

**Comment by FreeStyleFreeLunch** [comment] 2024-02-23 09:41
Thank you very much for your valuable suggestions. 
We will consider including hints about the principal modification spots in the README of subsequent versions. 
Upon reviewing the specific locations you mentioned, it's clear that modifications have indeed been made there.

**Closed** 2024-04-18 13:02 UTC
